[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

optimizer = true
optimizer_runs = 200

fs_permissions = [{ access = "read", path = "./"}]

[rpc_endpoints]
bsc = "https://bsc-dataseed.binance.org"
bsc_testnet = "https://data-seed-prebsc-1-s1.bnbchain.org:8545"

[etherscan]
bsc = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api", chain = 56 }
bsc_testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api", chain = 97 }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config