[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 200
via_ir = true

fs_permissions = [{ access = "read", path = "./"}]

[rpc_endpoints]
bsc = "https://bscrpc.com"
bsc_testnet = "https://data-seed-prebsc-1-s1.bnbchain.org:8545"

[etherscan]
bsc = { key = "${BSCSCAN_API_KEY}", chain = "bsc" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config